spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:file_extension
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

# Set Extension Configure
extension:
  max_custom_count: 200
  max_length: 20